#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11

squidclient -p 80 mgr: >/dev/null 2>&1
if [ $? -ne 0 ];then
	/etc/init.d/squid start
	logger -t "squid" "squid softlog restart squid service"
fi
