# ~/.bashrc: executed by bash(1) for non-login shells.
vmxhostname=${HOSTNAME%.vmx.cn}
export PS1='${vmxhostname}:\w\$ '
alias ls='ls --color'
export HISTFILESIZE=99999999
export HISTSIZE=999999999
shopt -s histappend
umask 022
alias ws='apt-cache search'
alias wi='apt-get install'
alias grep='grep --color=auto'
export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;35m\]\u@\h\[\033[00m\]:\[\033[01;31m\]\w\[\033[00m\]#"
