#!/bin/bash
#
# Manged by puppet.
# This file will be change if the nagios file format change.
# and don't edit this file by hand. 
#
type=$1
shift
for i in `echo "$@"`;do
	cat /tmp/cacti/$i
done|awk '
$0 ~/sec/ {
a[$1] +=$3
}
END {
        for ( i in a )print i" = "a[i]
}' >/tmp/cacti/$type
/usr/local/bin/cacti-update-host $type $type
